### ISSUE TITLE
Can't  install the Storm Kafka plugin

### ISSUE THREAD

**Issue by sharonpriel** [ghais/newrelic_storm_kafka#2]
Hi Guys,

I get the following error when I tried to install th plugin.
Please advice.

Thanks,
SP

INFO: New Relic monitor started
java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:127)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:644)
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
        at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44)
        at kafka.consumer.SimpleConsumer.getOrMakeConnection(SimpleConsumer.scala:142)
        at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:69)
        at kafka.consumer.SimpleConsumer.send(SimpleConsumer.scala:93)
        at kafka.javaapi.consumer.SimpleConsumer.send(SimpleConsumer.scala:68)
        at com.rekko.newrelic.storm.kafka.Kafka.getTopicMetaData(Kafka.java:93)
        at com.rekko.newrelic.storm.kafka.Kafka.getParitionsMetaData(Kafka.java:103)
        at com.rekko.newrelic.storm.kafka.Kafka.getOffsets(Kafka.java:53)
        at com.rekko.newrelic.storm.kafka.StormKafkaAgent.getLag(StormKafkaAgent.java:73)
        at com.rekko.newrelic.storm.kafka.StormKafkaAgent.pollCycle(StormKafkaAgent.java:61)
        at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:199)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[2015-02-12 07:57:27,544] ERROR com.rekko.newrelic.storm.kafka.StormKafkaAgent - nulljava.nio.channels.UnresolvedAddressException

**Comment by sharonpriel** [comment]
Now I get this error - Why it looking for partition_0?

[2015-02-15 13:33:54,721] INFO  com.rekko.newrelic.storm.kafka.StormKafkaAgent - current kafka offsets for Kafka voting:{0=0, 1=1, 2=0, 3=0, 4=0, 5=0, 6=1, 7=0}
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /kafkastorm/id/partition_0
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1155)
        at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:302)
        at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:291)
        at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:107)
        at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:287)
        at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:279)
        at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:41)
        at com.rekko.newrelic.storm.kafka.StormKafkaAgent.getStormOffsets(StormKafkaAgent.java:105)
        at com.rekko.newrelic.storm.kafka.StormKafkaAgent.getLag(StormKafkaAgent.java:75)
        at com.rekko.newrelic.storm.kafka.StormKafkaAgent.pollCycle(StormKafkaAgent.java:61)
        at com.newrelic.metrics.publish.Runner$PollAgentsRunnable.run(Runner.java:199)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[2015-02-15 13:33:54,741] ERROR com.rekko.newrelic.storm.kafka.StormKafkaAgent - KeeperErrorCode = NoNode for /kafkastorm/id/partition_0org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /kafkastorm/id/partition_0

**Comment by sharonpriel** [comment]
This is my config file:

          "name" : "Kafka voting",
          "kafka.topic" : "version1",
          "kafka.broker": "johny-kafka1.c.tidy-reporter-815.internal:9092",
          "storm.zk.host": "johny-zookeeper2.c.tidy-reporter-815.internal:2181",
          "storm.zk.path": "/kafkastorm"

**Comment by ghais** [comment]
@sharonpriel I believe the problem comes from the storm.zk.path.

Assume you create the following SpoutConfig

``` java
//SpoutConfig(BrokerHosts hosts, String topic, String zkRoot, String id)
SpoutConfig config = new SpoutConfig("johny-zookeeper2.c.tidy-reporter-815.internal:2181", "version1", "/kafkastorm", "version1_id");
```

It would translate to the following config

``` json
{
      "name" : "Kafka voting",
      "kafka.topic" : "version1",
      "kafka.broker": "johny-kafka1.c.tidy-reporter-815.internal:9092",
      "storm.zk.host": "johny-zookeeper2.c.tidy-reporter-815.internal:2181",
      "storm.zk.path": "/kafkastorm/version1_id"
}
```

The difference being the storm.zk.path. This config must point to where storm stores the offset in zookeeper and normally it is the concatenation of the  zkRoot and the id from the SpoutConfig constructor

**Comment by ghais** [comment]
An easy way to check what storm.zk.path should be is to launch your zookeeper-client and do:

```
ls /kafkastorm
```

**Comment by ghost** [comment]
Thanks ghais, I'll try it and update.
